In [7]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error

In [8]:
df = pd.DataFrame(pd.read_csv("car data.csv"))
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0
...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0

In [9]:
df["Age_car"]=df["Year"].apply(lambda x : 2023-x);
df

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner,Age_car
0,ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0,9
1,sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0,10
2,ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0,6
3,wagon r,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0,12
4,swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0,9
...,...,...,...,...,...,...,...,...,...,...
296,city,2016,9.50,11.60,33988,Diesel,Dealer,Manual,0,7
297,brio,2015,4.00,5.90,60000,Petrol,Dealer,Manual,0,8
298,city,2009,3.35,11.00,87934,Petrol,Dealer,Manual,0,14
299,city,2017,11.50,12.50,9000,Diesel,Dealer,Manual,0,6
300,brio,2016,5.30,5.90,5464,Petrol,Dealer,Manual,0,7

In [13]:
x = df[["Age_car","Kms_Driven","Fuel_Type","Seller_Type","Transmission"]]
y = df["Selling_Price"]
x = pd.get_dummies(x)

In [14]:
X_train, X_test, Y_train, Y_test =train_test_split(x,y,test_size=0.2,random_state=42)

In [15]:
model = LinearRegression()
z = model.fit(X_train,Y_train)

In [17]:
pre = model.predict(X_test)

In [19]:
r2 = r2_score(Y_test,pre)
print(r2)
mse = mean_squared_error(Y_test,pre)
print(mse)
print(model.coef_)
print(model.intercept_)

0.591149566336626
9.418108720809972
[-2.79387747e-01 -4.48042783e-06 -2.55192308e+00  3.85735270e+00
 -1.30542962e+00  2.05551251e+00 -2.05551251e+00  2.40151693e+00
 -2.40151693e+00]
8.983338776811973