In [1]:
from bs4 import BeautifulSoup
import pandas as pd

In [2]:
with open("flipkart.html","r",encoding="utf-8") as f:
     data = f.read()
soup = BeautifulSoup(data,"html.parser")

In [3]:
x=soup.find_all("div",{"class":"_3pLy-c row"})
n=[]
r=[]
s=[]
b=[]
d=[]
o=[]
for i in x:
    name=i.find("div",{"class":"_4rR01T"}).text
    n.append(name)
    rate=i.find("div",{"class":"_3LWZlK"}).text
    r.append(rate)
    sto=i.find("li",{"class":"rgWa7D"}).text
    s.append(sto)
    batt=i.find_all("li",{"class":"rgWa7D"})
    ba=""
    for j in batt:
        if "Battery" in j.text:
            ba=j.text;
            break;
    b.append(ba)
    dis=i.find("div",{"class":"_30jeq3 _1_WHN1"}).text
    d.append(dis)
    ori=i.find("div",{"class":"_3I9_wc _27UcVY"})
    if ori:
        ori=ori.text
    else:
        ori=0
    o.append(ori)    
    
df=pd.DataFrame({"name":n,"rating":r,"storage":s,"battery":b,"discount":d,"origin":o})
df

,name,rating,storage,battery,discount,origin
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹39,999","₹40,999"
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,"₹39,999","₹40,999"
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹49,999","₹1,01,999"
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹44,999","₹95,999"
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹49,999","₹74,999"
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,"₹49,999","₹74,999"
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,"₹40,999","₹45,999"
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹46,999","₹47,999"
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,"₹49,999","₹1,01,999"
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,"₹47,349","₹47,999"
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,"₹38,849","₹47,999"
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,"₹44,999","₹95,999"
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹49,999","₹57,990"
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,"₹47,999","₹57,990"
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,"₹48,999",0
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,"₹46,999",0
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,"₹49,999",0
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,4000 mAh Battery,"₹46,999","₹48,900"
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,"₹49,999",0
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹43,990","₹79,990"
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹43,900","₹79,990"
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,"₹49,999","₹57,999"
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,"₹48,999","₹54,990"
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,"₹48,880","₹84,999"

In [4]:
num=[]
for i in d:
    i=i[1:]
    i=i.replace(",","")
    i=int(i)
    num.append(i)
df["discount"]=num

In [5]:
num1=[]
for i in o:
    if i!=0:
        i=i[1:]
        i=i.replace(",","")
        i=int(i)
        num1.append(i)
    else:
        num1.append(0)
df["origin"]=num1

In [6]:
df

,name,rating,storage,battery,discount,origin
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,40999,45999
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,46999,47999
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,47349,47999
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,38849,47999
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,49999,57990
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,47999,57990
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,48999,0
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,46999,0
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,49999,0
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,4000 mAh Battery,46999,48900
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,49999,0
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43990,79990
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43900,79990
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,49999,57999
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,48999,54990
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,48880,84999

In [22]:
df["price"]=df["origin"]-df["discount"]
df["price"]=df["price"]/df["origin"]
df

,name,rating,storage,battery,discount,origin,price,rom,ram
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,0.024391,32 GB ROM,3 GB RAM
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,0.024391,32 GB ROM,3 GB RAM
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,0.509809,128 GB ROM,8 GB RAM
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,0.531256,128 GB ROM,8 GB RAM
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,0.333338,256 GB ROM,12 GB RAM
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,0.333338,256 GB ROM,12 GB RAM
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,40999,45999,0.108698,256 GB ROM,8 GB RAM
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,46999,47999,0.020834,256 GB ROM,12 GB RAM
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,0.509809,128 GB ROM,8 GB RAM
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,47349,47999,0.013542,256 GB ROM,12 GB RAM
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,38849,47999,0.190629,128 GB ROM,8 GB RAM
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,0.531256,128 GB ROM,8 GB RAM
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,49999,57990,0.137800,256 GB ROM,12 GB RAM
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,47999,57990,0.172288,256 GB ROM,12 GB RAM
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,48999,0,-inf,256 GB ROM,12 GB RAM
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,46999,0,-inf,256 GB ROM,12 GB RAM
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,49999,0,-inf,256 GB ROM,12 GB RAM
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,4000 mAh Battery,46999,48900,0.038875,128 GB ROM,NO RAM
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,49999,0,-inf,128 GB ROM,8 GB RAM
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43990,79990,0.450056,256 GB ROM,8 GB RAM
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43900,79990,0.451181,256 GB ROM,8 GB RAM
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,49999,57999,0.137933,128 GB ROM,8 GB RAM
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,48999,54990,0.108947,256 GB ROM,8 GB RAM
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,48880,84999,0.424934,256 GB ROM,12 GB RAM

In [23]:
import numpy as np
def per(price):
    if price==-np.inf:
        return "No Discount"
    else:
        return int(price*100)
df["price"]=df["price"].apply(per)
df

,name,rating,storage,battery,discount,origin,price,rom,ram
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,2,32 GB ROM,3 GB RAM
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,2,32 GB ROM,3 GB RAM
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,50,128 GB ROM,8 GB RAM
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,53,128 GB ROM,8 GB RAM
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,33,256 GB ROM,12 GB RAM
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,33,256 GB ROM,12 GB RAM
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,40999,45999,10,256 GB ROM,8 GB RAM
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,46999,47999,2,256 GB ROM,12 GB RAM
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,50,128 GB ROM,8 GB RAM
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,47349,47999,1,256 GB ROM,12 GB RAM
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,38849,47999,19,128 GB ROM,8 GB RAM
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,53,128 GB ROM,8 GB RAM
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,49999,57990,13,256 GB ROM,12 GB RAM
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,47999,57990,17,256 GB ROM,12 GB RAM
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,48999,0,No Discount,256 GB ROM,12 GB RAM
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,46999,0,No Discount,256 GB ROM,12 GB RAM
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,49999,0,No Discount,256 GB ROM,12 GB RAM
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,4000 mAh Battery,46999,48900,3,128 GB ROM,NO RAM
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,49999,0,No Discount,128 GB ROM,8 GB RAM
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43990,79990,45,256 GB ROM,8 GB RAM
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43900,79990,45,256 GB ROM,8 GB RAM
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,49999,57999,13,128 GB ROM,8 GB RAM
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,48999,54990,10,256 GB ROM,8 GB RAM
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,48880,84999,42,256 GB ROM,12 GB RAM

In [20]:
rom=[]
ram=[]
for i in s:
    i1=i.split("|")
    ra=""
    ro=""
    if "RAM" in i1[0]:
        ra=i1[0]
    else :
        ra="NO RAM"
    if len(i1)!=1:
        if "ROM" in i1[1]:
            ro=i1[1]
        else :
            ro="NO ROM"
    else :
        if "ROM" in i1[0]:
            ro=i1[0]
        else :
            ro="NO ROM"
    ram.append(ra)
    rom.append(ro)
df["rom"]=rom
df["ram"]=ram
df

,name,rating,storage,battery,discount,origin,price,rom,ram
0,"Huawei P9 (Mystic Silver, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,1000,32 GB ROM,3 GB RAM
1,"Huawei P9 (Prestige Gold, 32 GB)",4.5,3 GB RAM | 32 GB ROM | Expandable Upto 128 GB,3000 mAh Battery,39999,40999,1000,32 GB ROM,3 GB RAM
2,"SAMSUNG Galaxy S22 Plus 5G (Phantom Black, 128...",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,52000,128 GB ROM,8 GB RAM
3,"SAMSUNG Galaxy Z Flip3 5G (Phantom Black, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,51000,128 GB ROM,8 GB RAM
4,"MOTOROLA Edge 30 Ultra (Interstellar Black, 25...",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,25000,256 GB ROM,12 GB RAM
5,"MOTOROLA Edge 30 Ultra (Starlight White, 256 GB)",4.2,12 GB RAM | 256 GB ROM,4610 mAh Lithium Battery,49999,74999,25000,256 GB ROM,12 GB RAM
6,"SAMSUNG Galaxy A54 5G (Awesome Violet, 256 GB)",4.3,8 GB RAM | 256 GB ROM | Expandable Upto 1 TB,5000 mAh Battery,40999,45999,5000,256 GB ROM,8 GB RAM
7,"OnePlus 8 (Glacial Green, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,46999,47999,1000,256 GB ROM,12 GB RAM
8,"SAMSUNG Galaxy S22 Plus 5G (Green, 128 GB)",4.5,8 GB RAM | 128 GB ROM,4500 mAh Lithium-ion Battery,49999,101999,52000,128 GB ROM,8 GB RAM
9,"OnePlus 8 (Interstellar Glow, 256 GB)",4.5,12 GB RAM | 256 GB ROM,4300 mAh Battery,47349,47999,650,256 GB ROM,12 GB RAM
10,"Mi 10T Pro (Cosmic Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Li-ion Polymer Battery,38849,47999,9150,128 GB ROM,8 GB RAM
11,"SAMSUNG Galaxy Z Flip3 5G (Cream, 128 GB)",4.3,8 GB RAM | 128 GB ROM,3300 mAh Lithium-ion Battery,44999,95999,51000,128 GB ROM,8 GB RAM
12,"vivo X70 Pro (Cosmic Black, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,49999,57990,7991,256 GB ROM,12 GB RAM
13,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.4,12 GB RAM | 256 GB ROM,4450 mAh Battery,47999,57990,9991,256 GB ROM,12 GB RAM
14,"OnePlus 9RT 5G (Hacker Black, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,48999,0,-48999,256 GB ROM,12 GB RAM
15,"OnePlus 9RT 5G (Nano Silver, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4500 mAh Battery,46999,0,-46999,256 GB ROM,12 GB RAM
16,"OnePlus 9 5G (Winter Mist, 256 GB)",4,12 GB RAM | 256 GB ROM,4500 mAh Battery,49999,0,-49999,256 GB ROM,12 GB RAM
17,"APPLE iPhone 11 (Red, 128 GB)",4.6,128 GB ROM,4000 mAh Battery,46999,48900,1901,128 GB ROM,NO RAM
18,"OnePlus 9 5G (Astral Black, 128 GB)",3.9,8 GB RAM | 128 GB ROM,4500 mAh Battery,49999,0,-49999,128 GB ROM,8 GB RAM
19,"Xiaomi 12 Pro 5G (Opera Mauve, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43990,79990,36000,256 GB ROM,8 GB RAM
20,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.2,8 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,43900,79990,36090,256 GB ROM,8 GB RAM
21,"realme GT 2 Pro (Steel Black, 128 GB)",4.2,8 GB RAM | 128 GB ROM,5000 mAh Lithium Ion Battery,49999,57999,8000,128 GB ROM,8 GB RAM
22,"vivo X70 Pro (Aurora Dawn, 256 GB)",4.5,8 GB RAM | 256 GB ROM,4450 mAh Battery,48999,54990,5991,256 GB ROM,8 GB RAM
23,"Xiaomi 12 Pro 5G (Couture Blue, 256 GB)",4.1,12 GB RAM | 256 GB ROM,4600 mAh Lithium Polymer Battery,48880,84999,36119,256 GB ROM,12 GB RAM