In [1]:
import requests
import json
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"

In [2]:
lat=23.033863
lon=72.585022
key="57ed3a63cbe79efa475d0ab0b2f29b27"
url=f"https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [3]:
new=data.json()
final=json.dumps(new,indent=5)
print(final)

{
     "coord": {
          "lon": 72.5873,
          "lat": 23.0258
     },
     "weather": [
          {
               "id": 711,
               "main": "Smoke",
               "description": "smoke",
               "icon": "50d"
          }
     ],
     "base": "stations",
     "main": {
          "temp": 312.16,
          "feels_like": 310.01,
          "temp_min": 312.16,
          "temp_max": 312.16,
          "pressure": 1004,
          "humidity": 15,
          "sea_level": 1004,
          "grnd_level": 999
     },
     "visibility": 5000,
     "wind": {
          "speed": 2.57,
          "deg": 240
     },
     "clouds": {
          "all": 0
     },
     "dt": 1779457589,
     "sys": {
          "type": 1,
          "id": 9049,
          "country": "IN",
          "sunrise": 1779409578,
          "sunset": 1779457595
     },
     "timezone": 19800,
     "id": 1279233,
     "name": "Ahmedabad",
     "cod": 200
}

In [4]:
df=pd.DataFrame({"name":[new["name"]],"timezone":[new["timezone"]],"country":[new["sys"]["country"]],"wind speed":[new["wind"]["speed"]],
                 "visibility":[new["visibility"]],"description":[new["weather"][0]["description"]]})
df

        name  timezone country  wind speed  visibility description
0  Ahmedabad     19800      IN        2.57        5000       smoke

In [5]:
lat=23.033863
lon=72.585022
key="57ed3a63cbe79efa475d0ab0b2f29b27"
url=f"https://api.openweathermap.org/data/2.5/forecast?lat={lat}&lon={lon}&appid={key}"
data=requests.get(url)
data.status_code

200

In [6]:
new=data.json()
final=json.dumps(new,indent=5)
print(final)

{
     "cod": "200",
     "message": 0,
     "cnt": 40,
     "list": [
          {
               "dt": 1779462000,
               "main": {
                    "temp": 312.18,
                    "feels_like": 310.03,
                    "temp_min": 310.73,
                    "temp_max": 312.18,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 15,
                    "temp_kf": 1.45
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.15,
                    "deg": 239,
                    "gust": 5.5
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 15:00:00"
          },
          {
               "dt": 1779472800,
               "main": {
                    "temp": 310.02,
                    "feels_like": 310.14,
                    "temp_min": 305.69,
                    "temp_max": 310.02,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 28,
                    "temp_kf": 4.33
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 3.03,
                    "deg": 214,
                    "gust": 4.72
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 18:00:00"
          },
          {
               "dt": 1779483600,
               "main": {
                    "temp": 306.97,
                    "feels_like": 307.57,
                    "temp_min": 304.37,
                    "temp_max": 306.97,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1001,
                    "humidity": 37,
                    "temp_kf": 2.6
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 4.84,
                    "deg": 259,
                    "gust": 7.55
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-22 21:00:00"
          },
          {
               "dt": 1779494400,
               "main": {
                    "temp": 303.12,
                    "feels_like": 305.73,
                    "temp_min": 303.12,
                    "temp_max": 303.12,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1002,
                    "humidity": 59,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 23
               },
               "wind": {
                    "speed": 4.92,
                    "deg": 275,
                    "gust": 8.85
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 00:00:00"
          },
          {
               "dt": 1779505200,
               "main": {
                    "temp": 305.34,
                    "feels_like": 307.15,
                    "temp_min": 305.34,
                    "temp_max": 305.34,
                    "pressure": 1010,
                    "sea_level": 1010,
                    "grnd_level": 1004,
                    "humidity": 47,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04d"
                    }
               ],
               "clouds": {
                    "all": 97
               },
               "wind": {
                    "speed": 5.3,
                    "deg": 283,
                    "gust": 6.59
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 03:00:00"
          },
          {
               "dt": 1779516000,
               "main": {
                    "temp": 311,
                    "feels_like": 311.4,
                    "temp_min": 311,
                    "temp_max": 311,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1003,
                    "humidity": 27,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 804,
                         "main": "Clouds",
                         "description": "overcast clouds",
                         "icon": "04d"
                    }
               ],
               "clouds": {
                    "all": 98
               },
               "wind": {
                    "speed": 4.87,
                    "deg": 265,
                    "gust": 5.93
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 06:00:00"
          },
          {
               "dt": 1779526800,
               "main": {
                    "temp": 314.7,
                    "feels_like": 315.6,
                    "temp_min": 314.7,
                    "temp_max": 314.7,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 1000,
                    "humidity": 22,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 39
               },
               "wind": {
                    "speed": 5.58,
                    "deg": 255,
                    "gust": 6.64
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 09:00:00"
          },
          {
               "dt": 1779537600,
               "main": {
                    "temp": 314.99,
                    "feels_like": 314.84,
                    "temp_min": 314.99,
                    "temp_max": 314.99,
                    "pressure": 1004,
                    "sea_level": 1004,
                    "grnd_level": 998,
                    "humidity": 19,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02d"
                    }
               ],
               "clouds": {
                    "all": 20
               },
               "wind": {
                    "speed": 6.1,
                    "deg": 285,
                    "gust": 6.03
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-23 12:00:00"
          },
          {
               "dt": 1779548400,
               "main": {
                    "temp": 309.31,
                    "feels_like": 310.09,
                    "temp_min": 309.31,
                    "temp_max": 309.31,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 32,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 3.65,
                    "deg": 224,
                    "gust": 6.29
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 15:00:00"
          },
          {
               "dt": 1779559200,
               "main": {
                    "temp": 306.22,
                    "feels_like": 307.26,
                    "temp_min": 306.22,
                    "temp_max": 306.22,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 41,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 4
               },
               "wind": {
                    "speed": 4.5,
                    "deg": 254,
                    "gust": 7.53
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 18:00:00"
          },
          {
               "dt": 1779570000,
               "main": {
                    "temp": 303.25,
                    "feels_like": 304.35,
                    "temp_min": 303.25,
                    "temp_max": 303.25,
                    "pressure": 1006,
                    "sea_level": 1006,
                    "grnd_level": 1000,
                    "humidity": 50,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 801,
                         "main": "Clouds",
                         "description": "few clouds",
                         "icon": "02n"
                    }
               ],
               "clouds": {
                    "all": 12
               },
               "wind": {
                    "speed": 5.94,
                    "deg": 264,
                    "gust": 10.14
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-23 21:00:00"
          },
          {
               "dt": 1779580800,
               "main": {
                    "temp": 301.82,
                    "feels_like": 304.07,
                    "temp_min": 301.82,
                    "temp_max": 301.82,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1002,
                    "humidity": 63,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 10
               },
               "wind": {
                    "speed": 4.66,
                    "deg": 284,
                    "gust": 8.8
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 00:00:00"
          },
          {
               "dt": 1779591600,
               "main": {
                    "temp": 304.43,
                    "feels_like": 306.45,
                    "temp_min": 304.43,
                    "temp_max": 304.43,
                    "pressure": 1009,
                    "sea_level": 1009,
                    "grnd_level": 1004,
                    "humidity": 51,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 803,
                         "main": "Clouds",
                         "description": "broken clouds",
                         "icon": "04d"
                    }
               ],
               "clouds": {
                    "all": 61
               },
               "wind": {
                    "speed": 5.95,
                    "deg": 267,
                    "gust": 7.54
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 03:00:00"
          },
          {
               "dt": 1779602400,
               "main": {
                    "temp": 311.01,
                    "feels_like": 311.41,
                    "temp_min": 311.01,
                    "temp_max": 311.01,
                    "pressure": 1008,
                    "sea_level": 1008,
                    "grnd_level": 1003,
                    "humidity": 27,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 802,
                         "main": "Clouds",
                         "description": "scattered clouds",
                         "icon": "03d"
                    }
               ],
               "clouds": {
                    "all": 43
               },
               "wind": {
                    "speed": 5.75,
                    "deg": 266,
                    "gust": 6.88
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 06:00:00"
          },
          {
               "dt": 1779613200,
               "main": {
                    "temp": 315.26,
                    "feels_like": 314.47,
                    "temp_min": 315.26,
                    "temp_max": 315.26,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 17,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 1
               },
               "wind": {
                    "speed": 5.97,
                    "deg": 279,
                    "gust": 6.35
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 09:00:00"
          },
          {
               "dt": 1779624000,
               "main": {
                    "temp": 315.21,
                    "feels_like": 314.04,
                    "temp_min": 315.21,
                    "temp_max": 315.21,
                    "pressure": 1003,
                    "sea_level": 1003,
                    "grnd_level": 998,
                    "humidity": 16,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01d"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 6.08,
                    "deg": 277,
                    "gust": 6.07
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "d"
               },
               "dt_txt": "2026-05-24 12:00:00"
          },
          {
               "dt": 1779634800,
               "main": {
                    "temp": 310.75,
                    "feels_like": 309.51,
                    "temp_min": 310.75,
                    "temp_max": 310.75,
                    "pressure": 1005,
                    "sea_level": 1005,
                    "grnd_level": 999,
                    "humidity": 21,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.75,
                    "deg": 271,
                    "gust": 9.04
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 15:00:00"
          },
          {
               "dt": 1779645600,
               "main": {
                    "temp": 305.35,
                    "feels_like": 306.72,
                    "temp_min": 305.35,
                    "temp_max": 305.35,
                    "pressure": 1007,
                    "sea_level": 1007,
                    "grnd_level": 1001,
                    "humidity": 45,
                    "temp_kf": 0
               },
               "weather": [
                    {
                         "id": 800,
                         "main": "Clear",
                         "description": "clear sky",
                         "icon": "01n"
                    }
               ],
               "clouds": {
                    "all": 0
               },
               "wind": {
                    "speed": 4.1,
                    "deg": 223,
                    "gust": 6.66
               },
               "visibility": 10000,
               "pop": 0,
               "sys": {
                    "pod": "n"
               },
               "dt_txt": "2026-05-24 18:00:00"
          },
          {

In [7]:
temp=[]
date=[]
time=[]
dis=[]
for i in new["list"]:
    temp.append(i["main"]["temp"])
    date.append(i["dt_txt"].split(" ")[0])
    time.append(i["dt_txt"].split(" ")[1])
    dis.append(i["weather"][0]["description"])    
df=pd.DataFrame({"temp":temp,"date":date,"time":time,"dis":dis})
df

      temp        date      time               dis
0   312.18  2026-05-22  15:00:00         clear sky
1   310.02  2026-05-22  18:00:00         clear sky
2   306.97  2026-05-22  21:00:00         clear sky
3   303.12  2026-05-23  00:00:00        few clouds
4   305.34  2026-05-23  03:00:00   overcast clouds
5   311.00  2026-05-23  06:00:00   overcast clouds
6   314.70  2026-05-23  09:00:00  scattered clouds
7   314.99  2026-05-23  12:00:00        few clouds
8   309.31  2026-05-23  15:00:00         clear sky
9   306.22  2026-05-23  18:00:00         clear sky
10  303.25  2026-05-23  21:00:00        few clouds
11  301.82  2026-05-24  00:00:00         clear sky
12  304.43  2026-05-24  03:00:00     broken clouds
13  311.01  2026-05-24  06:00:00  scattered clouds
14  315.26  2026-05-24  09:00:00         clear sky
15  315.21  2026-05-24  12:00:00         clear sky
16  310.75  2026-05-24  15:00:00         clear sky
17  305.35  2026-05-24  18:00:00         clear sky
18  303.16  2026-05-24  21:00:00         clear sky
19  301.34  2026-05-25  00:00:00         clear sky
20  304.56  2026-05-25  03:00:00         clear sky
21  312.18  2026-05-25  06:00:00         clear sky
22  316.57  2026-05-25  09:00:00         clear sky
23  315.58  2026-05-25  12:00:00         clear sky
24  309.19  2026-05-25  15:00:00         clear sky
25  305.29  2026-05-25  18:00:00         clear sky
26  302.65  2026-05-25  21:00:00         clear sky
27  301.86  2026-05-26  00:00:00         clear sky
28  304.81  2026-05-26  03:00:00         clear sky
29  311.51  2026-05-26  06:00:00         clear sky
30  315.83  2026-05-26  09:00:00         clear sky
31  315.40  2026-05-26  12:00:00         clear sky
32  308.40  2026-05-26  15:00:00         clear sky
33  305.13  2026-05-26  18:00:00         clear sky
34  302.81  2026-05-26  21:00:00         clear sky
35  301.79  2026-05-27  00:00:00         clear sky
36  304.42  2026-05-27  03:00:00         clear sky
37  311.68  2026-05-27  06:00:00         clear sky
38  316.17  2026-05-27  09:00:00         clear sky
39  315.86  2026-05-27  12:00:00         clear sky

In [9]:
def cel(tem):
    return tem-273.15
df["temp_c"]=df["temp"].apply(cel)
df

      temp        date      time               dis  temp_c
0   312.18  2026-05-22  15:00:00         clear sky   39.03
1   310.02  2026-05-22  18:00:00         clear sky   36.87
2   306.97  2026-05-22  21:00:00         clear sky   33.82
3   303.12  2026-05-23  00:00:00        few clouds   29.97
4   305.34  2026-05-23  03:00:00   overcast clouds   32.19
5   311.00  2026-05-23  06:00:00   overcast clouds   37.85
6   314.70  2026-05-23  09:00:00  scattered clouds   41.55
7   314.99  2026-05-23  12:00:00        few clouds   41.84
8   309.31  2026-05-23  15:00:00         clear sky   36.16
9   306.22  2026-05-23  18:00:00         clear sky   33.07
10  303.25  2026-05-23  21:00:00        few clouds   30.10
11  301.82  2026-05-24  00:00:00         clear sky   28.67
12  304.43  2026-05-24  03:00:00     broken clouds   31.28
13  311.01  2026-05-24  06:00:00  scattered clouds   37.86
14  315.26  2026-05-24  09:00:00         clear sky   42.11
15  315.21  2026-05-24  12:00:00         clear sky   42.06
16  310.75  2026-05-24  15:00:00         clear sky   37.60
17  305.35  2026-05-24  18:00:00         clear sky   32.20
18  303.16  2026-05-24  21:00:00         clear sky   30.01
19  301.34  2026-05-25  00:00:00         clear sky   28.19
20  304.56  2026-05-25  03:00:00         clear sky   31.41
21  312.18  2026-05-25  06:00:00         clear sky   39.03
22  316.57  2026-05-25  09:00:00         clear sky   43.42
23  315.58  2026-05-25  12:00:00         clear sky   42.43
24  309.19  2026-05-25  15:00:00         clear sky   36.04
25  305.29  2026-05-25  18:00:00         clear sky   32.14
26  302.65  2026-05-25  21:00:00         clear sky   29.50
27  301.86  2026-05-26  00:00:00         clear sky   28.71
28  304.81  2026-05-26  03:00:00         clear sky   31.66
29  311.51  2026-05-26  06:00:00         clear sky   38.36
30  315.83  2026-05-26  09:00:00         clear sky   42.68
31  315.40  2026-05-26  12:00:00         clear sky   42.25
32  308.40  2026-05-26  15:00:00         clear sky   35.25
33  305.13  2026-05-26  18:00:00         clear sky   31.98
34  302.81  2026-05-26  21:00:00         clear sky   29.66
35  301.79  2026-05-27  00:00:00         clear sky   28.64
36  304.42  2026-05-27  03:00:00         clear sky   31.27
37  311.68  2026-05-27  06:00:00         clear sky   38.53
38  316.17  2026-05-27  09:00:00         clear sky   43.02
39  315.86  2026-05-27  12:00:00         clear sky   42.71

In [12]:
fig = px.bar(df[df["time"]=="12:00:00"],x="date",y="temp_c")
fig.show()